name: iOS CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  ios:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: latest

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          curl -LO https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.66/hxcpp-4.3.66.zip
          haxelib install ./hxcpp-4.3.66.zip --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet

      - name: Enable HXCPP compile cache
        run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Rebuild Lime tools
        run: |
          haxelib dev lime $GITHUB_WORKSPACE
          haxelib run lime setup -alias -y -nocffi

      - name: Rebuild Lime (iOS)
        run: |
          lime rebuild ios -clean -eval -nocolor -nocffi -release

      - uses: actions/upload-artifact@v4
        with:
          name: iPhone-NDLL
          path: |
            ndll/iPhone/
            !**/.gitignore
            lime.png
          if-no-files-found: error
