name: Linux CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: latest

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          sudo apt-get install -qq libgl1-mesa-dev libglu1-mesa-dev libpulse-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
          curl -LO https://github.com/HaxeFoundation/hxcpp/releases/download/v4.3.66/hxcpp-4.3.66.zip
          haxelib install ./hxcpp-4.3.66.zip --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
          haxelib dev lime $GITHUB_WORKSPACE

      - name: Enable HXCPP compile cache
        run: |
          echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Rebuild Lime
        run: |
          haxelib run lime rebuild linux -32 -eval -nocolor -nocffi -release
          haxelib run lime rebuild linux -64 -eval -nocolor -nocffi -release

      - uses: actions/upload-artifact@v4
        with:
          name: Linux-NDLL
          path: |
            ndll/Linux/
            ndll/Linux64/
            !**/.gitignore
            lime.png
          if-no-files-found: error
